force-app/main/default/objects/FeatureSettings__c/FeatureSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FeatureSettings</label>
</CustomObject>

force-app/main/default/objects/FeatureSettings__c/fields/FeatureEnabled__c.field-meta.xml
<CustomField>
    <fullName>FeatureEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FeatureEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordTypeMapping__c/RecordTypeMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RecordTypeMapping</label>
</CustomObject>

force-app/main/default/objects/RecordTypeMapping__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>The name of a CountryCode picklist value.</description>
    <inlineHelpText>The name of a CountryCode picklist value.</inlineHelpText>
    <label>CountryCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordTypeMapping__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>The name of a picklist value in the Lead Industry picklist.</description>
    <inlineHelpText>The name of a picklist value in the Lead Industry picklist.</inlineHelpText>
    <label>Industry</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordTypeMapping__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <description>The name of the record type to apply to the Lead when the Industry and Country values match this custom setting&#39;s Industry and Country values.</description>
    <inlineHelpText>The name of the record type to apply to the Lead when the Industry and Country values match this custom setting&#39;s Industry and Country values.</inlineHelpText>
    <label>Record Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomSettingsService.cls
public with sharing class CustomSettingsService {
    
    //Return a record that shows whether the RecordTypeMapping feature is enabled
    public FeatureSettings__c getMapperEnablementRecord() {
        return FeatureSettings__c.getInstance();
    }

    //Update the org-level custom setting
    //Returns the original value
    public Boolean updateMapperEnablementRecord(Boolean newValue) {
        FeatureSettings__c enablementRecord = [Select Id, FeatureEnabled__c from FeatureSettings__c LIMIT 1];
        Boolean originalValue = enablementRecord.FeatureEnabled__c;

        enablementRecord.FeatureEnabled__c = newValue;
        update enablementRecord;

        return originalValue;
    }

    //Return a record that shows which record type name to use for the given countryCode
    //and industry values on a new lead.
    public RecordTypeMapping__c getRecordTypeMappingping(String countryCode, String industry) {
        RecordTypeMapping__c mapping = null;

        List<RecordTypeMapping__c> mappings =  [SELECT Id, RecordTypeName__c FROM RecordTypeMapping__c 
                WHERE CountryCode__c = :countryCode AND Industry__c = :industry];
        if (mappings.size() > 0) {
            mapping = mappings.get(0);
        }
        return mapping;
    }

    
}