force-app/main/default/objects/RecordTypeMapping__c/RecordTypeMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RecordTypeMapping</label>
</CustomObject>

force-app/main/default/objects/RecordTypeMapping__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <description>The name of the record type to apply to the Lead when the Industry and Country values match this custom setting&#39;s Industry and Country values.</description>
    <inlineHelpText>The name of the record type to apply to the Lead when the Industry and Country values match this custom setting&#39;s Industry and Country values.</inlineHelpText>
    <label>Record Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MappingService.cls
public with sharing class MappingService {
    
    CustomSettingsService customSettings;

    public MappingService() {
        this.customSettings = new CustomSettingsService();
    }

    public String getRecordTypeName(String countryCode, String industry) {
        RecordTypeMapping__c mapping = this.customSettings.getRecordTypeMappingping(countryCode, industry);
        if (mapping != null) {
            return mapping.RecordTypeName__c;
        } else {
            return 'Default Lead';
        }
    }
}